version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8001:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: db_robinhood
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .db:/var/lib/mysql
    ports:
      - 3366:3306
